/// this class are contains all the constants
/// that has been used all over the sdk.
class PeppermintConstants {
  PeppermintConstants._();

  static const List<String> fileTypes = [
    'mp3',
    'mp4',
    'mov',
    'png',
    'jpg',
    'jpeg',
  ];

  static const List<String> adjectives = [
    'Affectionate',
    'agreeable',
    'amiable',
    'bright',
    'charming',
    'creative',
    'determined',
    'diligent',
    'diplomatic ',
    'dynamic',
    'energetic',
    'friendly',
    'funny',
    'generous',
    'giving',
    'gregarious',
    'hardworking',
    'helpful',
    'kind',
    'likable',
    'loyal',
    'patient',
    'polite',
    'sincere',
  ];

  static const List<String> animals = [
    'ant',
    'bear',
    'bee',
    'bird',
    'butterfly',
    'camel',
    'cat',
    'caterpillar',
    'chicken',
    'cow',
    'crab',
    'crocodile',
    'deer',
    'dog',
    'dolphin',
    'donkey',
    'duck',
    'elephant',
    'fish',
    'frog',
    'giraffe',
    'goat',
    'hamster',
    'hedgehog',
    'horse',
    'jellyfish',
    'ladybird',
    'sheep',
    'lion',
    'mole',
    'monkey',
    'mouse',
    'octopus',
    'owl',
    'panda',
    'penguin',
    'pig',
    'pony',
    'rabbit',
    'seahorse',
    'snake',
    'spider',
    'starfish',
    'stingray',
    'tiger',
    'turkey',
    'turtle',
    'unicorn',
    'whale',
    'worm',
    'zebra',
    'pigeon',
    'dinosaur',
    'dragon',
    'kangaroo',
    'clownfish',
    'rhinoceros',
    'toad',
    'puppy',
    'hippo',
    'rat',
    'ostrich',
    'peacock',
  ];
}
